import React from 'react';
import { ActivityInput } from '../types';
import { Map } from 'lucide-react';

interface CoverPageProps {
  meta: ActivityInput;
}

const CoverPage: React.FC<CoverPageProps> = ({ meta }) => {
  return (
    <div className="w-full max-w-[210mm] min-h-[297mm] mx-auto bg-gradient-to-br from-yellow-200 via-orange-100 to-yellow-50 p-12 text-center shadow-lg page-break mb-8 print:mb-0 print:shadow-none relative overflow-hidden pdf-no-shadow flex flex-col">
      
      {/* Decorative Elements */}
      <div className="absolute top-0 left-0 w-32 h-32 bg-yellow-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
      <div className="absolute top-0 right-0 w-32 h-32 bg-orange-400 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
      
      <div className="relative z-10 border-8 border-dashed border-slate-800 flex-grow rounded-3xl p-8 flex flex-col items-center justify-between bg-white/50 backdrop-blur-sm">
        
        <div className="space-y-4">
            <div className="inline-flex items-center justify-center w-24 h-24 bg-slate-800 rounded-full text-white mb-6">
                <Map className="w-12 h-12" />
            </div>
            <h1 className="text-5xl md:text-6xl font-comic font-bold text-slate-800 leading-tight">
                My <br/>
                <span className="text-yellow-600">Travel</span><br/>
                Activity Book
            </h1>
        </div>

        <div className="space-y-2">
            <p className="text-2xl font-bold text-slate-600 uppercase tracking-widest">Destination</p>
            <div className="text-4xl md:text-5xl font-comic font-black text-indigo-600 transform -rotate-2">
                {meta.destinationCity ? `${meta.destinationCity}, ` : ''}{meta.destinationCountry}
            </div>
        </div>

        <div className="w-full">
            <div className="border-t-4 border-slate-800 w-1/3 mx-auto mb-8"></div>
            <p className="text-slate-500 font-comic">Generated by Nano Banana</p>
        </div>

      </div>
    </div>
  );
};

export default CoverPage;